import React from 'react';
import { Metadata } from 'next';
import { ShieldAlert, Calculator, Info, CheckCircle2 } from 'lucide-react';

export const metadata: Metadata = {
  title: 'FlowUPI — Financial & Utility Disclaimer',
  description: 'FlowUPI Disclaimer explaining software utility scope, educational zero-MDR simulation context, and non-binding calculator estimates.',
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8 py-4">
      {/* Header */}
      <div className="border-[1.5px] border-border-subtle bg-bg-surface p-6 sm:p-8 shadow-neo space-y-3">
        <div className="flex items-center gap-2 text-status-warning font-black text-xs uppercase tracking-wider">
          <ShieldAlert className="h-4 w-4" />
          <span>LEGAL & FINANCIAL DISCLAIMER</span>
        </div>

        <h1 className="text-2xl sm:text-3xl font-black uppercase text-txt-primary tracking-tight">
          Financial & Software Disclaimer
        </h1>

        <p className="text-xs sm:text-sm font-bold text-txt-secondary leading-relaxed">
          Last Updated: September 17, 2026
        </p>

        <p className="text-xs text-txt-muted leading-relaxed border-t border-border-subtle pt-3">
          This document clarifies the operational scope and legal nature of the FlowUPI application and its calculation tools.
        </p>
      </div>

      {/* Structured Disclaimer Boxes */}
      <div className="border-[1.5px] border-border-subtle bg-bg-surface p-6 sm:p-8 shadow-neo space-y-6 text-xs text-txt-secondary leading-relaxed">
        {/* Section 1 */}
        <section className="space-y-2">
          <h2 className="text-sm font-black text-txt-primary uppercase tracking-wider flex items-center gap-2">
            <span>1. Software Utility & Academic Demonstration</span>
          </h2>
          <p>
            FlowUPI is a client-side software utility designed for merchant QR code scanning, payment intent URI formatting, bill micro-tranching, and group expense tracking. The sub-₹2,000 micro-tranching feature is designed for educational, academic demonstration, and algorithmic simulation of NPCI 0% MDR interchange guidelines.
          </p>
        </section>

        {/* Section 2 */}
        <section className="space-y-2 border-t border-border-subtle pt-6">
          <h2 className="text-sm font-black text-txt-primary uppercase tracking-wider flex items-center gap-2">
            <span>2. No Banking, Financial, or Investment Advice</span>
          </h2>
          <p>
            FlowUPI does NOT provide banking services, financial advice, tax advice, investment recommendations, or legal counsel. Nothing contained in this application should be construed as an offer, solicitation, or official financial settlement advice.
          </p>
        </section>

        {/* Section 3 */}
        <section className="space-y-2 border-t border-border-subtle pt-6">
          <h2 className="text-sm font-black text-txt-primary uppercase tracking-wider flex items-center gap-2">
            <Calculator className="h-4 w-4 text-brand-cyan" />
            <span>3. MDR Calculator Informational Nature</span>
          </h2>
          <p>
            All calculations generated by the MDR Surcharge Calculator are informational estimates based solely on the numerical inputs provided by the user and general interchange guidelines (e.g. 0.4% surcharge on merchant transactions exceeding ₹2,000). Actual interchange fees, MDR charges, acquiring bank settlements, and taxes vary depending on specific merchant category codes (MCC), bank agreements, card networks, and regulatory updates.
          </p>
        </section>

        {/* Section 4 */}
        <section className="space-y-2 border-t border-border-subtle pt-6">
          <h2 className="text-sm font-black text-txt-primary uppercase tracking-wider flex items-center gap-2">
            <span>4. Third-Party Trademarks & Logos</span>
          </h2>
          <p>
            All product names, logos, brands, and trademarks referenced within FlowUPI (such as NPCI, UPI, Google Pay / GPay, PhonePe, Paytm, BHIM, BharatQR) belong to their respective owners. Reference to these brands does not imply endorsement, affiliation, or sponsorship.
          </p>
        </section>
      </div>
    </div>
  );
}
